name: UKit
main: cat.nyaa.ukit.SpigotLoader
version: ${project.version}
softdepend:
  - Vault
  - ECore
  - Essentials
  - EssentialsChat
  - EssentialsDiscord
  - LuckPerms
  - LockettePro
api-version: 1.20
folia-supported: true
libraries:
  - org.xerial:sqlite-jdbc:3.44.1.0
authors:
  - Nyaacat Community
commands:
  ukit:
    description: "ukit commands. Use /ukit help for more information."
    usage: /ukit <args...>
    aliases:
      - u